[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- 라이브러리 ---
lib_deps =
    bblanchon/ArduinoJson@^7.0.4

; ============================
; USB 업로드 환경 (복구/처음 업로드용)
; ============================
[env:esp32dev_usb]
extends = env:esp32dev
upload_speed = 921600

; ============================
; OTA 업로드 환경 (평소 사용)
; ============================
[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.0.4
upload_flags =
    --auth=ota1234
    --port=3232
    --host_port=48266